### ISSUE TITLE
coverage reporter fails with remap-istanbul >= 0.8.2

### ISSUE THREAD

**Issue by jp7677** [sshev/karma-remap-coverage#12]
Hi there,

karma-remap-coverage 0.1.3 currently fails with remap-istanbul 0.8.2 with 
```
TypeError: remap is not a function
    at RemapCoverageReporter.onCoverageComplete (node_modules/karma-remap-coverage/remap-coverage.js:23:23)
```

Version 0.8 of remap-istanbul has seen quite some refactorings, see https://github.com/SitePen/remap-istanbul/commit/a990033511fd69358a34942e7cdd70afaaf12af2. The `remap-istanbul/lib/remap` module has been moved to `remap-istanbul/src/remap`, I guess that's one of the reason why it currently aborts with an error.

Regards,
Jens

PS: Thanks for your work on karma-remap-coverage, it works pretty cool!

**Comment by sshev** [comment]
@jp7677 it works fine with latest `remap-istanbul@0.8.4`
looks they've reverted back some breaking changes

**Comment by sshev** [comment]
fix version in `0.1.4` https://github.com/sshev/karma-remap-coverage/commit/8b353018d0a1c71f4713f5db3649ea1e623ae3b4

**Comment by jp7677** [comment]
Hi @sshev, confirmed, works perfectly again. Thanks a lot!
